name: Enviar Lembretes
on:
  schedule:
    - cron: '*/5 * * * *'      # Executa a cada 5 minutos
  workflow_dispatch:            # Permite executar manualmente

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install firebase-admin nodemailer
      - run: node sendReminders.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
